In [ ]:
import pandas as pd
import requests
pd.set_option('display.max_columns', None) # so we can see all columns in a wide Dataframe
import time
import numpy as np

In [ ]:
test_url = 'https://stats.nba.com/stats/leagueLeaders?LeagueID=00&PerMode=Totals&Scope=S&Season=2013-14&SeasonType=Regular%20Season&StatCategory=PTS'

In [ ]:
r = requests.get(url=test_url).json()

In [ ]:
table_headers = r['resultSet']['headers']

In [ ]:
pd.DataFrame(r['resultSet']['rowSet'], columns = table_headers)

,PLAYER_ID,RANK,PLAYER,TEAM_ID,TEAM,GP,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS,EFF,AST_TOV,STL_TOV
0,201142,1,Kevin Durant,1610612760,OKC,81,3122,849,1688,0.503,192,491,0.391,703,805,0.873,58,540,598,445,103,59,285,174,2593,2572,1.56,0.36
1,2546,2,Carmelo Anthony,1610612752,NYK,77,2982,743,1643,0.452,167,415,0.402,459,541,0.848,145,477,622,242,95,51,198,224,2112,1942,1.22,0.48
2,2544,3,LeBron James,1610612748,MIA,77,2902,767,1353,0.567,116,306,0.379,439,585,0.750,81,452,533,488,121,26,270,126,2089,2255,1.81,0.45
3,201567,4,Kevin Love,1610612750,MIN,77,2797,650,1421,0.457,190,505,0.376,520,633,0.821,224,739,963,341,59,35,196,136,2010,2328,1.74,0.30
4,201933,5,Blake Griffin,1610612746,LAC,80,2863,718,1359,0.528,12,44,0.273,482,674,0.715,192,565,757,309,92,51,224,265,1930,2082,1.38,0.41
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
477,202354,475,Dexter Pittman,1610612737,ATL,2,3,0,1,0.000,0,0,0.000,0,2,0.000,3,0,3,0,0,0,0,0,0,0,0.00,0.00
478,203548,475,Elias Harris,1610612747,LAL,2,11,0,1,0.000,0,0,0.000,0,0,0.000,1,0,1,1,1,0,0,0,0,2,0.00,0.00
479,2735,475,Josh Childress,1610612740,NOP,4,24,0,0,0.000,0,0,0.000,0,0,0.000,0,3,3,2,1,0,1,1,0,5,2.00,1.00
480,2767,475,Royal Ivey,1610612760,OKC,2,5,0,2,0.000,0,1,0.000,0,0,0.000,0,1,1,0,0,0,0,1,0,-1,0.00,0.00
481,203091,475,Royce White,1610612758,SAC,3,9,0,1,0.000,0,0,0.000,0,0,0.000,0,0,0,0,0,0,0,2,0,-1,0.00,0.00

In [ ]:
df_cols = ['Year', 'Season_type'] + table_headers

In [ ]:
pd.DataFrame(columns=df_cols)

Empty DataFrame
Columns: [Year, Season_type, PLAYER_ID, RANK, PLAYER, TEAM_ID, TEAM, GP, MIN, FGM, FGA, FG_PCT, FG3M, FG3A, FG3_PCT, FTM, FTA, FT_PCT, OREB, DREB, REB, AST, STL, BLK, TOV, PF, PTS, EFF, AST_TOV, STL_TOV]
Index: []

In [ ]:
headers = {
    'accept': '*/*',
    'accept-encoding': 'gzip, deflate, br, zstd',
    'accept-language': 'en-US,en;q=0.9',
    'connection':'keep-alive',
    'host': 'stats.nba.com',
    'origin': 'https://www.nba.com',
    'referer': 'https://www.nba.com/',
    'sec-fetch-dest': 'empty',
    'sec-fetch-mode': 'cors',
    'sec-fetch-site': 'same-site',
    'user-agent': 'Mozilla/5.0 (iPhone; CPU iPhone OS 16_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Mobile/15E148 Safari/604.1'
}

In [ ]:
print(r.keys())

dict_keys(['resource', 'parameters', 'resultSet'])

In [ ]:
import time
import requests
import pandas as pd
import numpy as np

season_types = ['Regular%20Season', 'Playoffs']
years = ['2013-14', '2014-15', '2015-16', '2016-17', '2017-18', '2018-19', '2019-20', '2020-21', '2021-22', '2022-23', '2023-24']

# Initialize variables
df = pd.DataFrame()

begin_loop = time.time()

for y in years:
    for s in season_types:
        api_url = f'https://stats.nba.com/stats/leagueLeaders?LeagueID=00&PerMode=Totals&Scope=S&Season={y}&SeasonType={s}&StatCategory=PTS'
        try:
            headers = {
                'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36',
                'Referer': 'https://www.nba.com/',
                'Origin': 'https://www.nba.com',
                'Accept-Language': 'en-US,en;q=0.9',
            }
            r = requests.get(url=api_url, headers=headers).json()
            if 'resultSet' in r:
                temp_df1 = pd.DataFrame(r['resultSet']['rowSet'], columns=table_headers)
                temp_df2 = pd.DataFrame({'Year': [y] * len(temp_df1), 'Season_type': [s] * len(temp_df1)})
                temp_df3 = pd.concat([temp_df2, temp_df1], axis=1)
                df = pd.concat([df, temp_df3], axis=0)
                print(f'Finished scraping data for the {y} {s}.')
            else:
                print(f"Warning: 'resultSet' not found for {y} {s}")
        except Exception as e:
            print(f"Error occurred while processing {y} {s}: {e}")
        lag = np.random.uniform(low=5, high=40)
        print(f'...waiting {round(lag,1)} seconds')
        time.sleep(lag)

print(f'Process completed! Total run time: {round((time.time()-begin_loop)/60,2)} minutes')
df.to_excel('nba_player_data.xlsx', index=False)

Finished scraping data for the 2013-14 Regular%20Season.
...waiting 22.0 seconds
Finished scraping data for the 2013-14 Playoffs.
...waiting 35.4 seconds
Finished scraping data for the 2014-15 Regular%20Season.
...waiting 12.9 seconds
Finished scraping data for the 2014-15 Playoffs.
...waiting 17.6 seconds
Finished scraping data for the 2015-16 Regular%20Season.
...waiting 8.6 seconds
Finished scraping data for the 2015-16 Playoffs.
...waiting 14.2 seconds
Finished scraping data for the 2016-17 Regular%20Season.
...waiting 21.8 seconds
Finished scraping data for the 2016-17 Playoffs.
...waiting 37.5 seconds
Finished scraping data for the 2017-18 Regular%20Season.
...waiting 8.1 seconds
Finished scraping data for the 2017-18 Playoffs.
...waiting 9.7 seconds
Finished scraping data for the 2018-19 Regular%20Season.
...waiting 35.0 seconds
Finished scraping data for the 2018-19 Playoffs.
...waiting 13.3 seconds
Finished scraping data for the 2019-20 Regular%20Season.
...waiting 9.4 seconds
Finished scraping data for the 2019-20 Playoffs.
...waiting 8.5 seconds
Finished scraping data for the 2020-21 Regular%20Season.
...waiting 19.5 seconds
Finished scraping data for the 2020-21 Playoffs.
...waiting 32.1 seconds
Finished scraping data for the 2021-22 Regular%20Season.
...waiting 16.7 seconds
Finished scraping data for the 2021-22 Playoffs.
...waiting 36.7 seconds
Finished scraping data for the 2022-23 Regular%20Season.
...waiting 19.6 seconds
Finished scraping data for the 2022-23 Playoffs.
...waiting 26.8 seconds
Finished scraping data for the 2023-24 Regular%20Season.
...waiting 6.5 seconds
Finished scraping data for the 2023-24 Playoffs.
...waiting 34.4 seconds
Process completed! Total run time: 7.48 minutes

In [ ]:
df

,Year,Season_type,PLAYER_ID,RANK,PLAYER,TEAM_ID,TEAM,GP,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS,EFF,AST_TOV,STL_TOV
0,2013-14,Regular%20Season,201142,1,Kevin Durant,1610612760,OKC,81,3122,849,1688,0.503,192,491,0.391,703,805,0.873,58,540,598,445,103,59,285,174,2593,2572,1.56,0.36
1,2013-14,Regular%20Season,2546,2,Carmelo Anthony,1610612752,NYK,77,2982,743,1643,0.452,167,415,0.402,459,541,0.848,145,477,622,242,95,51,198,224,2112,1942,1.22,0.48
2,2013-14,Regular%20Season,2544,3,LeBron James,1610612748,MIA,77,2902,767,1353,0.567,116,306,0.379,439,585,0.750,81,452,533,488,121,26,270,126,2089,2255,1.81,0.45
3,2013-14,Regular%20Season,201567,4,Kevin Love,1610612750,MIN,77,2797,650,1421,0.457,190,505,0.376,520,633,0.821,224,739,963,341,59,35,196,136,2010,2328,1.74,0.30
4,2013-14,Regular%20Season,201933,5,Blake Griffin,1610612746,LAC,80,2863,718,1359,0.528,12,44,0.273,482,674,0.715,192,565,757,309,92,51,224,265,1930,2082,1.38,0.41
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209,2023-24,Playoffs,1641765,198,Olivier-Maxence Prosper,1610612742,DAL,3,9,0,2,0.000,0,0,0.000,0,0,0.000,0,3,3,1,0,0,0,0,0,2,0.00,0.00
210,2023-24,Playoffs,1631115,198,Orlando Robinson,1610612748,MIA,1,2,0,1,0.000,0,1,0.000,0,0,0.000,0,1,1,1,0,0,0,0,0,1,0.00,0.00
211,2023-24,Playoffs,203933,198,T.J. Warren,1610612750,MIN,3,11,0,2,0.000,0,1,0.000,0,0,0.000,2,1,3,1,0,0,0,0,0,2,0.00,0.00
212,2023-24,Playoffs,201152,198,Thaddeus Young,1610612756,PHX,1,4,0,0,0.000,0,0,0.000,0,0,0.000,0,0,0,0,0,0,0,0,0,0,0.00,0.00
213,2023-24,Playoffs,203648,198,Thanasis Antetokounmpo,1610612749,MIL,2,5,0,0,0.000,0,0,0.000,0,0,0.000,0,0,0,0,1,1,0,1,0,2,0.00,0.00

In [ ]:
df.to_excel('nba_player_data.xlsx')